version: '3.8'

services:
  app:
    build: .
    command: >
      bash -c "rm -f /usr/src/app/tmp/pids/server.pid &&
                RAILS_ENV=${RAILS_ENV} bundle exec rails db:migrate &&
                RAILS_ENV=${RAILS_ENV} bundle exec rails db:seed &&
                RAILS_ENV=${RAILS_ENV} bundle exec rails assets:precompile &&
                RAILS_ENV=${RAILS_ENV} bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    container_name: travel_postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    container_name: travel_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - app-network
  
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge